version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=desistenao_admin
      - POSTGRES_PASSWORD=d3s1stena0
      - POSTGRES_DB=DNDB
    ports:
    - '5430:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/desistenao_db
volumes:
  postgres_db:
    driver: local